workshop_name: "Workshop 11 - Classificacion"
response_file: "W11_test_solutions.xlsx"
response_column: "Churn_sol" #nom de la columna dels respostes correctes
id_column: "id"
user_column: "Email"
prediction_column: "Churn" #nom de la columna dels alumnes
results_path: "./AdD/"
resultats_rdata: "W11.RData"
metric: "RMSE"
task_type: "classification"